USE COMPANY;
SELECT CONCAT(Fname, " ", Minit, " ", Lname) AS "Full name", Ssn, Dno AS "Dept. Id.", Dname AS "Dept. Name"
FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.Ssn = DEPARTMENT.Mgr_ssn
WHERE Ssn IN (SELECT Mgr_ssn
FROM DEPARTMENT
WHERE Dnumber IN (SELECT DISTINCT Dno
FROM WORKS_ON JOIN EMPLOYEE ON WORKS_ON.Essn = EMPLOYEE.Ssn
WHERE Hours < 40));
